### ISSUE TITLE
Add hourly rate options

### ISSUE THREAD

**Issue by kevinpapst** [kimai/kimai#111]
- [x] add a column "hourly rate" to `activity` entity
- [x] add a column "hourly rate" to `project` entity
- [x] add service to calculate the best fitting rate in the order: activity, project, user setting
- [x] adjust `import` command to import possible rates

**TODO**: write spec
