### ISSUE TITLE
Add native desktop notification

### ISSUE THREAD

**Issue by kevinpapst** [kimai/kimai#116]
Native notification should be possible via an event. The first implementation should be used for the use-case "After stopping an entry display total duration and rate".

## A notification should contain
- [ ] Headline
- [ ] Text
- [ ] Kimai logo

## Tasks
- [ ] add event subscriber for `app.native.notification`
- [ ] add event model with title, text
- [ ] send `app.native.notification` after stopping an entry with total duration
- [ ] add developer documentation

## Details

If the user has not yet given permission to send notifications, an alert box (or a notification bar at the top) should be shown requesting the user to activate notifications.

![grafik](https://user-images.githubusercontent.com/941794/35541172-bbd10750-0559-11e8-8645-75957349a264.png)

Add section in user settings/preferences about Notifications:

![grafik](https://user-images.githubusercontent.com/941794/35541255-2f846a34-055a-11e8-807e-c6d569affcb7.png)

**Comment by kevinpapst** [comment]
No voting within one year => closing.
